
use_frameworks!


platform :osx, "10.12"
workspace 'Workspace'
project 'ObjectMapperPlaygrounds'


def all_pods
  pod 'ObjectMapper'
end


target 'ObjectMapperPlaygrounds' do
  all_pods
end


target 'Tests' do
  all_pods
end

