// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Resource Loading",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Resource Loading",
            targets: ["AppModule"],
            bundleIdentifier: "com.lopsae.resourceLoading",
            teamIdentifier: "BDK5WHBJY2",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .coffee),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "../ResourcesPackage")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ResourcesPackage", package: "resourcespackage")
            ],
            path: "."
        )
    ]
)