#!/bin/bash

# Reading parameters with getopt
# DONT USE GETOPT, IT DOES NOT PROPERLY SUPPORT SPACES


if [[ $# = 0 ]]; then
	echo 'Using suggested serving:'
	echo "$0 -ax -d 'double dparam' -y -b -zc cparam -- first 'second element'"
	set -- -ax -d 'double dparam' -y -b -zc cparam -- first 'second element'
	echo
fi


originalParams=("$@")
optstring='abc:d:'


echo 'Initial parameters'
echo "\$@: $@"
./printParams "$@"
echo


echo "Using optstring: $optstring"
echo


echo 'getopt is recomended with $*, but $@ seems to work with spaces'
echo 'getopt "$@"'
params=$(getopt $optstring "$@")
getoptStatus=$?
echo


echo 'Illegal options are reported, but left out of the output'
echo "\$params: $params"
echo


echo 'Produced output is to be set as current parameters'
set -- $params
echo "\$@: $@"
echo


echo 'And read with a `for`'
for param; do
	case $param in
		-[ab])
			echo "option: $param"
			shift
			;;
		-[cd])
			echo "option: $param"
			echo "argument: $2"
			shift 2
			;;
		--)
			echo "dashes: $param"
			shift
			break
			;;
		*)
			echo "Something else: $param"
			shift
			;;
	esac
done
echo


echo 'Remaining parameters'
./printParams "$@"
echo


echo 'Something really messy happened there, parameter were lost or skipped'
echo


echo 'Restore original params'
set -- "${originalParams[@]}"
echo "\$@: $@"
./printParams "$@"
echo


echo 'getopt is recomended with $*'
echo 'getopt $*'
params=$(getopt $optstring $*)
getoptStatus=$?
echo


echo 'Illegal options are reported'
echo 'With $* options end with the first space found'
echo "\$params: $params"
echo


echo 'Produced output is to be set as current parameters'
set -- $params
echo "\$@: $@"
echo


echo 'And read with a `for`'
for param; do
	case $param in
		-[ab])
			echo "option: $param"
			shift
			;;
		-[cd])
			echo "option: $param"
			echo "argument: $2"
			shift 2
			;;
		--)
			echo "dashes: $param"
			shift
			break
			;;
		*)
			echo "Something else: $param"
			shift
			;;
	esac
done
echo


echo 'Remaining parameters'
./printParams "$@"
echo


echo 'Please dont use getopt'

