#!/bin/bash

# Reading parameters with getopt
# DONT USE GETOPT, IT DOES NOT PROPERLY SUPPORT SPACES

# TODO add recomended serving
# TODO add example code for getopt
# TODO add example of how it horribly fais with spaces paired with options
# TODO add example of how it messes up spaces in the remaining parameters


if [[ $# = 0 ]]; then
	echo 'Using suggested serving:'
	echo "$0 -a -d 'double dparam' -b -c cparam -- first 'second element'"
	set -- -a -d 'double dparam' -b -c cparam -- first 'second element'
	echo
fi


echo 'Initial parameters'
./printParams "$@"
echo


echo 'getopts $*'
echo $(getopt abc:d: $*)
echo

echo 'getopts "$@"'
echo $(getopt abc:d: "$@")
echo


# Options parsing
# recomende to use is $*
params=$(getopt abc:d: "$@")
# params=$(getopt abc:d: $*)
getoptStatus=$?

echo 'Params parsed'
echo "$params"
echo

set -- $params

if [[ $getoptStatus != 0 ]]; then
	echo 'Invalid options' >&2
	exit 1
fi

for param; do
	case "$param" in
		-[ab])
			echo "option: $param"
			shift
			;;
		-[cd])
			echo "option: $param"
			echo "argument: $2"
			shift; shift
			;;
		--)
			echo "dashes: $param"
			shift
			break
			;;
	esac
done
echo

echo 'Remaining parameters'
./printParams "$@"
echo


exit


echo "Original parameters"
echo "\$@: $@"


echo
echo 'Printing each value in "$@"'
counter=1
for param in "$@"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done


# All whitespace is lost by getopt...
params=$(getopt abc:d: "$@")
paramReturn=$?

echo
if [[ $paramReturn = 0 ]]; then
	echo "Parameters parsed correctly"
else
	echo "Parameters parsed failed"
fi


echo 'Parsed params'
echo "\$params: $params"
echo 'Printing each value in "$params[@]"'
counter=1
for param in "${params[@]}"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done


set -- $params

echo
echo 'After set -- $params'
echo 'Printing each value in "$@"'
counter=1
for param in "$@"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done


