#!/bin/bash

if [[ $# = 0 ]]; then
	echo 'Using suggested serving:'
	echo "$0 first 'second element' 'and   third'"
	set -- first 'second element' 'and   third'
	echo
fi


echo 'Passing $@'
./paramsPrint $@
echo


echo 'Passing "$@"'
./paramsPrint "$@"
echo


echo 'Using $single $spaces'
single='agony'
spaces='and joy'
echo "\$single: $single \$spaces: $spaces"
echo


echo 'Passing $single'
./paramsPrint $single
echo


echo 'Passing $spaces'
./paramsPrint $spaces
echo


echo 'Passing "$spaces"'
./paramsPrint "$spaces"
echo

echo 'Passing $single$spaces'
./paramsPrint $single$spaces
echo


echo 'Passing "$single$spaces"'
./paramsPrint "$single$spaces"
echo


echo 'Passing "$single $spaces"'
./paramsPrint "$single $spaces"
echo


echo 'Passing $(./paramsPrint $single)'
output=$(./paramsPrint $single)
echo "$output"
echo


echo 'Passing $(./paramsPrint $spaces)'
output=$(./paramsPrint $spaces)
echo "$output"
echo


echo 'Passing $(./paramsPrint "$spaces")'
output=$(./paramsPrint "$spaces")
echo "$output"
echo


echo 'Copying into an array ("$@")'
array=("$@")
echo "\${array[@]}: ${array[@]}"
echo

echo 'Passing ${array[@]}'
./paramsPrint ${array[@]}
echo

echo 'Passing "${array[@]}"'
./paramsPrint "${array[@]}"
echo


read -d '' piped <<"HEREDOC"
Lorem    ipsum
dolor sit amet
HEREDOC


if [[ ! -t 0 ]]; then
	piped=$(cat)
else
	echo 'Using suggested serving:'
	echo "$piped"
	echo
fi


echo 'Piped:'
echo "$piped"
echo


echo 'Passing $piped'
./paramsPrint $piped
echo


echo 'Passing "$piped"'
./paramsPrint "$piped"
echo


echo 'Passing $piped with IFS=\n'
IFS=$'\n'
./paramsPrint $piped
unset IFS
echo 


echo 'Splitting $piped'
IFS=$'\n'
for item in $piped; do
	echo "for \$piped: $item"
	array+=("$item")
done
unset IFS
echo


echo 'Passing "${array[@]}"'
./paramsPrint "${array[@]}"


