#!/bin/bash

if [[ $# = 0 ]]; then
	echo 'Using suggested serving:'
	echo "$0 first 'second element' 'and   third'"
	set -- first 'second element' 'and   third'
	echo
fi


echo 'Passing $@'
./printParams $@
echo


echo 'Passing "$@"'
./printParams "$@"
echo


echo 'Using $empty $single $spaces'
empty=''
single='agony'
spaces='and joy'
echo "\$empty: $empty \$single: $single \$spaces: $spaces"
echo


echo 'Passing $empty'
./printParams $empty
echo


echo 'Passing "$empty"'
./printParams "$empty"
echo


echo 'Passing $empty "$empty"'
./printParams $empty "$empty"
echo


echo 'Passing "$empty" "$empty"'
./printParams "$empty" "$empty"
echo


echo 'Passing $single'
./printParams $single
echo


echo 'Passing $spaces'
./printParams $spaces
echo


echo 'Passing "$spaces"'
./printParams "$spaces"
echo

echo 'Passing $single$spaces'
./printParams $single$spaces
echo


echo 'Passing "$single$spaces"'
./printParams "$single$spaces"
echo


echo 'Passing "$single $spaces"'
./printParams "$single $spaces"
echo


echo 'Passing $(./printParams $single)'
output=$(./printParams $single)
echo "$output"
echo


echo 'Passing $(./printParams $spaces)'
output=$(./printParams $spaces)
echo "$output"
echo


echo 'Passing $(./printParams "$spaces")'
output=$(./printParams "$spaces")
echo "$output"
echo


echo 'Using empty array: ()'
array=()
echo "\${array[@]}: ${array[@]}"
echo


echo 'Passing ${array[@]}'
./printParams ${array[@]}
echo

echo 'Passing "${array[@]}"'
./printParams "${array[@]}"
echo


echo 'Copying into an array ("$@")'
array=("$@")
echo "\${array[@]}: ${array[@]}"
echo


echo 'Passing ${array[@]}'
./printParams ${array[@]}
echo


echo 'Passing "${array[@]}"'
./printParams "${array[@]}"
echo


read -d '' piped <<"HEREDOC"
Lorem    ipsum
dolor sit amet
HEREDOC


if [[ ! -t 0 ]]; then
	piped=$(cat)
else
	echo 'Using suggested serving:'
	echo "$piped"
	echo
fi


echo 'Piped:'
echo "$piped"
echo


echo 'Passing $piped'
./printParams $piped
echo


echo 'Passing "$piped"'
./printParams "$piped"
echo


echo 'Passing $piped with IFS=\n'
IFS=$'\n'
./printParams $piped
unset IFS
echo 


echo 'Splitting $piped'
IFS=$'\n'
for item in $piped; do
	echo "for \$piped: $item"
	array+=("$item")
done
unset IFS
echo


echo 'Passing "${array[@]}"'
./printParams "${array[@]}"


