#!/bin/bash


if [[ -t 0 && -t 1 ]]; then
	echo 'Suggested servings:'
	echo "ls | $0"
	echo "$0 | cat"
	echo "ls | $0 | cat"
	echo
fi


read -d '' loremipsum <<"loremipsum"
Lorem ipsum dolor
sit amet consectetuer
adipiscing elit
loremipsum


if [[ -t 0 ]]; then
	echo 'Input from terminal, using loremipsum'
	from='term'
	content="$loremipsum"
else
	echo 'Input piped in'
	from='pipe'
	content=$(cat)
fi


if [[ -t 1 ]]; then
	echo 'Output to terminal'
	to='term'
else
	echo 'Output to pipe'
	to='pipe'
fi
echo





IFS=$'\n'
for contentLine in $content; do
	echo "$from -> $to: $contentLine"
done
unset IFS
echo

