#!/bin/bash

if [[ $# -ge 2 ]]; then
	echo "Error: printRandom can only receive one argument" >&2
	exit 1
fi

intRegex='^[0-9]+$'
if [[ $# -eq 1 && ! $1 =~ $intRegex ]];then
	echo 'Error: printRandom can only receive an intenger as single argument' >&2
	exit 1
fi

length=10
if [[ $# -eq 1 ]]; then
	length=$1
fi

cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-z0-9' | fold -w $length | head -n 1
