#!/bin/bash


# if used as
# echo "cosa" | printPipes
# Receiving piped standart input: cosa
# output going to terminal

# if used as
# printPipes
# No input, cat? read?
# Output going to terminal

# if used as
# echo "sumthin sumthin" | printPipes
# Piped input:
# sumthin sumthin
# Output going to terminal

# if used as
# printPipes | cat
# No input, lorem ipsum
# Output going to pipe!

read -d '' loremipsum <<"loremipsum"
Lorem ipsum dolor
sit amet consectetuer
adipiscing elit
loremipsum


if [[ -t 1 ]]; then
	echo 'Output going to terminal'
	outputPrefix='terminal:'
else
	echo 'Output going to pipe'
	outputPrefix='piped-out:'
fi
echo


if [ -t 0 ]; then
	echo 'Input from terminal, using loremipsum'
	content="$loremipsum"
else
	echo 'Input piped in'
	content=$(cat)
fi


IFS=$'\n'
for contentLine in $content; do
	echo "$outputPrefix $contentLine"
done
unset IFS
echo

