#!/bin/bash

if [[ $# = 0 ]]; then
	echo 'No parameters'
	exit
fi


# First parameter is the optstring
optstring="$1"
shift


./printParams "$@"
echo

# OPTERR=0
echo "\$OPTERR:$OPTERR"


while getopts $optstring option; do
	echo "\$option:$option \$OPTIND:$OPTIND \$OPTARG:$OPTARG"
done


echo "\$OPTIND: $OPTIND"

